name: Android CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
#      - name: Run gradle tests
#        run: ./gradlew test --stacktrace
#      - name: Build Gradle Project
#        run: ./gradlew build --stacktrace
      - name: Build APK Debug
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: $(date +'%Y-%m-%d') - APK debug generated
          path: app/build/outputs/apk/debug/
