name: Android CI

on:
  pull_request:
    branches: "main"
  push: 
    branches: "main"

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run gradle tests
        run: ./gradlew test --stacktrace
      - name: Build Gradle Project
        run: ./gradlew build --stacktrace
      - name: Build APK Debug
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: APK debug generated
          path: app/build/outputs/apk/debug/
